language: rust

rust:
  - nightly
  - stable
  - beta

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang
    - llvm-dev

install:
- export CXX="clang++" CC="clang"

script: cargo test --all
