[package]
name = "hllvm"
version = "0.1.0"
authors = ["Dylan McKay <dylanmckay34@gmail.com>"]

[workspace]

[dependencies]
hllvm-sys = { version = "0.1.0", path = "src/sys" }
lazy_static = "0.1"
libc = "0.2"
