[package]
name = "llvm-sys"
version = "0.1.0"
authors = ["Dylan McKay <dylanmckay34@gmail.com>"]

build = "build.rs"

[lib]
path = "lib.rs"

[dependencies]
libc = "0.2"
ncurses = "5.84" # Required to link LLVM

[build-dependencies]
gcc = "0.3"
